[backend]
id = "harbor.0.20.0"
kind = "local"
adapter = "harbor"
bmp_version = "0.1"
executable = "/root/.local/share/uv/tools/harbor/bin/harbor"
version = "0.20.0"
digest = "998eb086b23784f317a336d2cf6d306896ea1cb6fc8998806b2ecacba2ebad7c"

[backend.defaults]
environment_type = "docker"
network_mode = "none"
